services:
  - type: web
    name: leadify-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: NODE_ENV
        value: "production"
